name: second level print
description: print some inputs
inputs:
  t2Input:
    description: foo
    required: true

runs:
  using: "composite"
  steps:
    - name: print
      run: |
        # printf 'some envs: '$GITHUB_WORKSPACE'\n' >> some-file
        # printf 'some envs: '${GITHUB_WORKSPACE}'\n' >> some-file
        # printf 'some envs: '${{ env.GITHUB_WORKSPACE }}'\n' >> some-file
        if [ ${{ inputs.t2Input == 'true' }} = true]; then
          echo "true"
        fi
        if [ ${{ inputs.t2Input == 'false' }} = true]; then
          echo "true"
        fi
        cat some-file
      shell: bash

    - name: print 2
      run: |
        echo "running"
      if: ${{ inputs.t2Input == true }}
      shell: bash

    - name: print 2
      run: |
        echo "running"
      if: ${{ inputs.t2Input == 'false' }}
      shell: bash
