name: second level print
description: print some inputs
inputs:
  t2Input:
    description: foo
    required: true

runs:
  using: "composite"
  steps:
    - name: print
      run: |
        printf 'some envs: '$GITHUB_WORKSPACE'\n' >> some-file
        printf 'some envs: '${GITHUB_WORKSPACE}'\n' >> some-file
        printf 'some envs: '${{ env.GITHUB_WORKSPACE }}'\n' >> some-file

        cat some-file
      shell: bash
