name: Call an action
on:
  workflow_dispatch:

jobs:
  call-action-1:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "foobar"
    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: action1
        uses: ./.github/actions/print-env
        with:
          myInput: $GITHUB_WORKSPACE
      - name: action2
        uses: ./.github/actions/print-env
        with:
          myInput: ${GITHUB_WORKSPACE}
      - name: action3
        uses: ./.github/actions/print-env
        # doesnt work
        # with:
        #   myInput: ${{ GITHUB_WORKSPACE }}
      - name: action4
        uses: ./.github/actions/print-env
        with:
          myInput: ${{ env.GITHUB_WORKSPACE }}
